### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [EVS-GIS/fct-qgis#4]
# Problem

Since this plugin is a fork, Does the upstream owner give consent for you to publish the plugin under your name if an existing one didn't exist ?

**Comment by sdunesme** [comment]
The owner of the upstream repository has left the hydromorphology business. A former colleague remains quoted as the plugin's author (Christophe Rousson), but no longer wishes to participate. I've left a message on the README of the old repository indicating that development of the plugin continues on this one, but I don't have the necessary rights to delete it and create a redirection.

**Comment by sdunesme** [comment]
Thank you for approval!
